version: '3'
services:
  cloud9:
    image: eeacms/cloud9
    environment:
      - C9_WORKSPACE=${PWD}
    volumes:
      - ${PWD}:${PWD}
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=cloud9'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:cloud9.${PROJECT_BASE_URL:-domain.local}'
  web:
    image: feature/php71-dev-7
    environment:
      - DOCUMENT_ROOT=${PWD}/web
      - XDEBUG_CONFIG=idekey=cloud9ide remote_connect_back=0 remote_host=172.20.0.1
      - COMPOSER_PROCESS_TIMEOUT=600
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    labels:
      - 'traefik.backend=web'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL:-domain.local}'
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-drupal}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    labels:
      - 'traefik.backend=mysql'
      - 'traefik.port=3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-root}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      PMA_ABSOLUTE_URI: 'http://phpmyadmin.${PROJECT_BASE_URL:-domain.local}'
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.frontend.rule=Host:phpmyadmin.${PROJECT_BASE_URL:-domain.local}'
  solr:
    image: fpfis/solr5
    labels:
      - 'traefik.backend=solr'
      - 'traefik.port=8983'
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  backstopjs:
#    image: backstopjs/backstopjs
#    volumes:
#      - ${PWD}:/src
#  portainer:
#    image: portainer/portainer
#    command: --no-auth -H unix:///var/run/docker.sock
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    labels:
#      - 'traefik.backend=portainer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL:-domain.local}'
#  varnish:
#    image: fpfis/varnish-d7
#    environment:
#      - BACKEND_HOST=web
#      - BACKEND_PORT=8080
#      - VCL_DIR=/test/nexteuropa_varnish/vcls
#      - VCL_FILE=default.vcl
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6080'
