version: '3'
services:
  cloud9:
    image: fpfis/cloud9
    environment:
      - C9_IP=${C9_IP:-0.0.0.0}
      - C9_PORT=${C9_PORT:-8080}
      - C9_USER=${C9_USER:-}
      - C9_PASS=${C9_PASS:-}
      - C9_WORKSPACE=${PWD}
    volumes:
      - ${PWD}:${PWD}
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=cloud9'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:cloud9.${PROJECT_BASE_URL:-domain.local}'
      - 'traefik.frontend.auth.basic=root:$$apr1$$maTXzIMX$$YXkPh8TX5lm2dpFGb6GrQ.'
  web:
    image: fpfis/php71-dev-7
    hostname: ${PROJECT_BASE_URL:-domain.local}
    environment:
      - DOCUMENT_ROOT=${PWD}/web
      - XDEBUG_CONFIG="idekey=cloud9ide remote_host=cloud9 remote_connect_back=0"
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - ~/.ssh:/root/.ssh/
    labels:
      - 'traefik.backend=web'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL:-domain.local}'
      - 'traefik.frontend.auth.basic=root:$$apr1$$maTXzIMX$$YXkPh8TX5lm2dpFGb6GrQ.'
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-drupal}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    labels:
      - 'traefik.backend=mysql'
      - 'traefik.port=3306'
  solr:
    image: fpfis/solr5
    labels:
      - 'traefik.backend=solr'
      - 'traefik.port=8983'
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  backstopjs:
#    image: backstopjs/backstopjs
#    volumes:
#      - ${PWD}:/src
#  portainer:
#    image: portainer/portainer
#    command: --no-auth -H unix:///var/run/docker.sock
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    labels:
#      - 'traefik.backend=portainer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL:-domain.local}'
#  varnish:
#    image: fpfis/varnish-d7
#    environment:
#      - BACKEND_HOST=web
#      - BACKEND_PORT=8080
#      - VCL_DIR=/test/nexteuropa_varnish/vcls
#      - VCL_FILE=default.vcl
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6080'
