version: '3'

services:
    cloud9:
        #image: fpfis/cloud9
        build: ./resources/docker/cloud9
        environment:
            C9_IP: ${C9_IP:-0.0.0.0}
            C9_PORT: ${C9_PORT:-8080}
            C9_USER: ${C9_USER:-}
            C9_PASS: ${C9_PASS:-}
            C9_WORKSPACE: ${C9_WORKSPACE:-/var/www}
            DOCKER_HOST: ${DOCKER_HOST:-tcp://10.132.0.2:2375}
        volumes:
            - ${PWD}:/var/www
        labels:
            - 'traefik.backend=cloud9'
            - 'traefik.port=8080'
            - 'traefik.frontend.rule=Host:cloud9.${HOSTNAME:-localhost}'
            - 'traefik.frontend.auth.basic=root:$$apr1$$maTXzIMX$$YXkPh8TX5lm2dpFGb6GrQ.'
    httpd:
        #image: fpfis/httpd-php-dev:7.1
        build: ./resources/docker/httpd
        volumes:
            - ${PWD}:/var/www
            - ~/.ssh:/root/.ssh/
            - ~/.composer:/root/.composer
        working_dir: /var/www
        environment:
              XDEBUG_CONFIG: "idekey=cloud9ide remote_host=cloud9 remote_connect_back=0"
              TERM: xterm
              COLUMNS: 201
        labels:
             - 'traefik.backend=httpd'
             - 'traefik.port=8080'
             - 'traefik.frontend.rule=Host:${HOSTNAME:-localhost}'
    mail:
        image: tophfr/mailcatcher
        labels:
            - 'traefik.smtp.backend=mail'
            - 'traefik.smtp.port=25'
            - 'traefik.catcher.port=80'
            - 'traefik.catcher.frontend.rule=Host:mailcatcher.${HOSTNAME:-localhost}'
            - 'traefik.catcher.frontend.auth.basic=root:$$apr1$$maTXzIMX$$YXkPh8TX5lm2dpFGb6GrQ.'
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-drupal}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
        labels:
             - 'traefik.backend=mysql'
             - 'traefik.port=3306'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_PORT: 3306
            PMA_HOST: mysql
            PMA_USER: ${MYSQL_USER:-root}
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
            PMA_ABSOLUTE_URI: 'http://phpmyadmin.${PROJECT_BASE_URL:-domain.local}'
            PHP_UPLOAD_MAX_FILESIZE: 1G
            PHP_MAX_INPUT_VARS: 1G
        labels:
            - 'traefik.backend=pma'
            - 'traefik.frontend.rule=Host:phpmyadmin.${PROJECT_BASE_URL:-domain.local}'
            - 'traefik.frontend.auth.basic=root:$$apr1$$maTXzIMX$$YXkPh8TX5lm2dpFGb6GrQ.'
    solr:
        image: fpfis/solr5
        labels:
            - 'traefik.backend=solr'
            - 'traefik.port=8983'
    traefik:
        image: traefik
        command: -c /dev/null --web --docker.endpoint=${DOCKER_HOST:-tcp://10.132.0.2:2375} --logLevel=INFO
        ports:
            - '80:80'
            - '8080:8080'
#  backstopjs:
#    image: backstopjs/backstopjs
#    volumes:
#      - ${PWD}:/src
#  portainer:
#    image: portainer/portainer
#    command: --no-auth -H unix:///var/run/docker.sock
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    labels:
#      - 'traefik.backend=portainer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL:-domain.local}'
#  varnish:
#    image: fpfis/varnish-d7
#    environment:
#      - BACKEND_HOST=web
#      - BACKEND_PORT=8080
#      - VCL_DIR=/test/nexteuropa_varnish/vcls
#      - VCL_FILE=default.vcl
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6080'
